language: node_js
node_js:
  - 4
  - 5
  - 6
  - 7
  - 8
  - 10
  - lts/*
  - node
deploy:
  - provider: npm
    email: twilio-ci@twilio.com
    api_key:
      secure: EQjq/aPzjHfKGhZE7Lh47DHcGYsnYXL9aEjEPX03CjhLy1QOjVH+qHeb5Ud5t+EVlmsTyK+xMkDuECgA4wb6n4rjaH7XZebMGrkijdQ5zg09qPD8TF5+/gBHIKPdRxlIXoinimsuYDhxvYf3Cq1YSFzZ4+/f/oJOqCjtcNraqQQrdm63WV12tp9fBB8Za2XUo0JTNs0zA4q1qfxp2NSicU9Wf7Cq8ppaV6mngQVd4Q/w/uyGUkOAq/zAjfVYMM0MUmzsPShEI/KaX9/XiUyTIJw+L4SNDHK+zq0Lj3w90oKWaIIioVcB4qi07d0aj0s5xZ8ZxZDr6640p5LpN/lZf5eCMb9ge81OL9Z7CBCtCe1AGk7EJAFBB4WZ9q6MFLfOv5TjEbdADSjbp+0NfhwdPbvrYsN5Z0TkV7sFnQ2LjAwo2CXUu7JItDqKDVuuB36PjPBSAkVN3gxPgUJsBSs1KSFb88ZoVIHLLBfE/vAQGXteBg9e/ScXmzk/59H45gMQozIOggI/3qcK6xaTVk5+IR76tgc1b+G3MGDUpqn4AQyX1wDdWJiIl8jXAJQ27ugqZr0PCKGf3sx/ZUGW03ax6vnb3vUaMce2E5ytLibNDU9vLDPz39gEVQVkV430+qCOC/WPYTOxGBblQLQXOVf8cIY42yzr4IApARs4gbOtllE=
    on:
      tags: true
      node: 10

notifications:
  slack:
    if: branch = master
    on_pull_requests: false
    on_success: never
    on_failure: change
    rooms:
      - secure: QawILOoaJQWghcHWYxFfibatqvka0INzDboLuzWEvdDpCbfHUd4FXXvMGLHBUoTiB2vvey0edCCaCsrMoqJEJ1fyYZYS4XuYN+XGN+FH2GAoKi+j07om9V1ChuUDcXGB+sqMTM09mGvRGk95hLzkI/bRzQVA+ITaRpdWKJYnD0zZWPuQXi6sLVyMQrHqVOYLyf3avN5mJyqncatZkCpMlhQJvn/aIM0wmToifM6HC1xp4lNU3Rq6h+gHyJP+TZZ5zBc1b388UQDjpLHAoB8ZpIqOlvQJ9cwRvSfqQUXWXZrAYS4wBZvq5Y2YpRm6sHZ6pfs/aCJpIVZ3tyTctqTnHlddesBfGyxzbVW/Wl7ewJUhtphxcaVNweuzVnVVj4ooQr58hKlvJtZlrE1wmEluQ0OL0zF4tfBmq3fonCgvWXiQGgGwEC/DmDSxZInGnyHGg3Ew/7SPBhoGWB+g1B90Og5RtyMe/IUbyRXM4jFPCPdv8IiE3zmDyzDVkbjh+YX06F2pYYFPoyFRNawKtx6vGrV0Ta/o08E3tPrtQKxGkwcn+6zIQVuXw9onswnkiZwCDajcI+Yyi/NP9+OK5bSDPIqnuFsMZoEROKGGRUfUFDGyEStw2WdGmMCGiSJjCEHP75l4u4nPhft8sk28/xUC6NjTWoJahthYW08dW+0MuQQ=
